server:
  port: 9999
spring:
  application:
    name: datagen
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081
orders:
  output-topic: orders